# ============================
# Puerto del servidor
# ============================
quarkus.http.port=8620

# ============================
# Base de datos PostgreSQL (Render)
# ============================
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://dpg-d40cqhu3jp1c73dnn5t0-a.oregon-postgres.render.com/casillervirtualbd
quarkus.datasource.username=casillervirtualbd_user
quarkus.datasource.password=kE2qe12vpv5yEBwDuEi9dUPLOD3NaLU0
quarkus.datasource.jdbc.driver=org.postgresql.Driver

# ============================
# Hibernate
# ============================
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.sql-load-script=no-file

# ============================
# CORS
# ============================
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,PUT,POST,DELETE,OPTIONS
quarkus.http.cors.headers=Accept,Authorization,Content-Type,X-Requested-With
quarkus.http.cors.access-control-allow-credentials=true

# ============================
# MAILER GMAIL - QUARKUS 3.26
# ============================

quarkus.mailer.from=nicoram572@gmail.com

# SMTP de Gmail
quarkus.mailer.host=smtp.gmail.com
quarkus.mailer.port=587

# Gmail usa STARTTLS obligatorio
quarkus.mailer.start-tls=REQUIRED
quarkus.mailer.ssl=false

# Credenciales
quarkus.mailer.username=nicoram572@gmail.com
quarkus.mailer.password=akgwjdzsbcvqwrvc

# Enviar correos reales
quarkus.mailer.mock=false
