# Puerto del servidor
quarkus.http.port=8620

# Configuración de la base de datos PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=casillervirtualbd_user
quarkus.datasource.password=kE2qe12vpv5yEBwDuEi9dUPLOD3NaLU0
quarkus.datasource.jdbc.url=jdbc:postgresql://dpg-d40cqhu3jp1c73dnn5t0-a.oregon-postgres.render.com:5432/casillervirtualbd?sslmode=require
quarkus.datasource.jdbc.driver=org.postgresql.Driver

# Configuración de Hibernate
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.sql-load-script=no-file

# ? Configuración CORS (para permitir acceso desde cualquier origen)
quarkus.http.cors=true
quarkus.http.cors.origins=/.*/
quarkus.http.cors.methods=GET,PUT,POST,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
quarkus.http.cors.access-control-allow-credentials=true

# (Antiguas configuraciones comentadas)
#postgresql://casillerovirtualbd_user:z6Cg3HkULVJ5YV0fXZWo3HwHE8zNIA9O@dpg-d3aumjd6ubrc739ak1ig-a.oregon-postgres.render.com/casillerovirtualbd
#spring.datasource.url=jdbc:postgresql://dpg-d3aumjd6ubrc739ak1ig-a.oregon-postgres.render.com/casillerovirtualbd
#spring.datasource.username=casillerovirtualbd_user
#spring.datasource.password=z6Cg3HkULVJ5YV0fXZWo3HwHE8zNIA9O
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
