# Puerto del servidor
quarkus.http.port=8620

# Configuraci�n de la base de datos PostgreSQL (Render)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://dpg-d40cqhu3jp1c73dnn5t0-a.oregon-postgres.render.com/casillervirtualbd
quarkus.datasource.username=casillervirtualbd_user
quarkus.datasource.password=kE2qe12vpv5yEBwDuEi9dUPLOD3NaLU0
quarkus.datasource.jdbc.driver=org.postgresql.Driver

# Configuraci�n de Hibernate
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.sql-load-script=no-file

# ==== CORS CORRECTAMENTE CONFIGURADO ====
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,PUT,POST,DELETE,OPTIONS
quarkus.http.cors.headers=Accept,Authorization,Content-Type,X-Requested-With
quarkus.http.cors.access-control-allow-credentials=true

# ==== Configuración del Mailer ====
# NOTA: Para producción, usar variables de entorno en lugar de valores hardcodeados
# Ejemplo: quarkus.mailer.username=${MAIL_USERNAME}
quarkus.mailer.host=smtp.gmail.com
quarkus.mailer.port=587
quarkus.mailer.username=nicoram572@gmail.com
quarkus.mailer.password=j7R_)*42@nE1V.
quarkus.mailer.from=nicoram572@gmail.com
# Valores válidos para start-tls: DISABLED, OPTIONAL, REQUIRED
quarkus.mailer.start-tls=REQUIRED
quarkus.mailer.ssl=false
